### ISSUE TITLE
Add DBSMigration integration tests

### ISSUE THREAD

**Issue by vkuznet** [dmwm/dbs2go#24]
We should add DBSMigration integration tests as following:
- setup two SQLIte databases
- inject data into one SQLite database, e.g. database-A
- create migration request to another database, e.g. database-B
- migrate single block and single dataset
- check details of migration block/dataset
   - check block/dataset attributes like size, number of files, events
   - check parentage of blocks/datasets

**Comment by vkuznet** [comment]
@d-ylee with this commit 1ac904d49e031008f522984f22f961978b2eeb3a I added code codebase required for DBS Migration test.  The new `test/migration_test.go` file contains everything we need to start the migration process integration tests. It starts four DBS servers, see description in a code, and code is ready to implement actual migration.

**Comment by vkuznet** [comment]
and, I updated DBS databases with this commit d94d584d74908a56fd88a5eb2418c242d08c1548. Please see `test/migration_test.go` for explanation which DB will be used for which process. In total, we'll have 6 DBS servers used in DBS Migration process, two pairs (DBSReader/DBSWriter) associated with two databases, and DBSMigrate and DBSMigration servers used for migration process.

**Comment by vkuznet** [comment]
@d-ylee , I disabled `TestMigrate` function in `test/migrate_test.go` since it requires change of logic due to asynchronous behavior of migration process. Please adjust it. The migration request now requires two servers, DBSMigrate and DBSMigration, where later will pick up migration request and move it through transition states. Therefore, the test should check for COMPLETED status after some time when DBSMigration server will perform the migration.

**Comment by d-ylee** [comment]
@vkuznet I also think everything is done here. If there isn't anything else you can think of to resolve this issue, I think it is safe to close this issue. Thanks!
