### ISSUE TITLE
Client API listBlockTrio not compatible with the Python version

### ISSUE THREAD

**Issue by amaltaro** [dmwm/dbs2go#35]
While testing the WMCore StepChain parentage fix CherryPy thread, basically this code:
https://github.com/dmwm/WMCore/blob/3882e1ff7c55fd9a3054807f9ab8aebd8029d769/src/python/WMCore/Services/DBS/DBS3Reader.py#L932

I noticed that there is an exception while we deal with the object retrieved from the `listBlockTrio` client API. It turns out that the output of this API comes in a different structure between the Python-based and the Go-based server.

Example for the python-based:
``` 
[{'661281877': [[1, 189], [1, 190], [1, 191],
``` 

while the go-based server returns:
```
[{'cfid': 661281877, 'l': 1, 'r': 1}, {'cfid': 661281877, 'l': 2, 'r': 1}, 
```

Here is a snippet of code to check this:
``` 
from dbs.apis.dbsClient import DbsApi

godbs = DbsApi(url = 'https://cmsweb-testbed.cern.ch/dbs/int/global/DBSReader/')
pydbs = DbsApi(url = 'https://cmsweb-testbed.cern.ch/dbspy/int/global/DBSReader/')

testbedBlock = "/VBF_HHTo2G2Tau_CV_1_C2V_1_C3_0_TuneCP5_13TeV-powheg-pythia8/RunIISummer20UL16MiniAODAPVv2-HIG_RunIISummer20UL16MiniAODAPVv2_02457_0_SC_6Steps_PU_May2022_Val_Alanv1-v11/MINIAODSIM#25f5a41e-00e8-4148-9f62-36e2125cef7f"

godbs.listBlockTrio(block_name=testbedBlock)
pydbs.listBlockTrio(block_name=testbedBlock)
``` 

Note that this should be crashing the production service as well, but I just had a look at the production reqmgr2-tasks log (reqmgr2-20220506-reqmgr2-tasks-7879c8775c-drn25.log) and I see parentage information being properly fetched and updated. I fail to understand why.

By the way, this is based on dbs3-client version 4.0.7

**Comment by amaltaro** [comment]
And here is why things are working in production, because we created an dbs3-client object with the DBSWriter url, not DBSReader. Which can be verified with:
```
>>> prodDbsApi = DbsApi(url = 'https://cmsweb.cern.ch/dbs/prod/global/DBSWriter/')
>>> prodDbsApi.listBlockTrio(block_name=prodBlock)
[{'833730077': [[1, 1301]]}]
```

**Comment by vkuznet** [comment]
@amaltaro , This is issue should be in DBSClient rather than here. Apparently it was missing in DBSClient, we had aggregation for [`parentDSTrio`](https://github.com/dmwm/DBSClient/commit/b810e2ed5656dff8bebef5ad8b1a793a1964a0be) but missed to add aggregation to `listBlockTrio` DBS API. The fix is here: https://github.com/dmwm/DBSClient/pull/70
With this fix I got the following result:
```
go [{661281877: [[1, 1], [1, 2] ...

py [{'661281877': [[1, 189], [1, 190], ...
```
Please note two things, the order of aggregates is different as it depends on order how oracle return results. But it is not critical since the entire list contains all results anyway. More importantly, the key in go output is integer type as it is returned by ORACLE, while in python it is a string. I will not change the data-type as it violates the ORACLE one. Pleae have a look at PR and patch your DBSClient to test your results and let me know.

**Comment by amaltaro** [comment]
Thanks for the prompt fix, Valentin. I left a comment on something that needs to be fixed in your PR.

Regarding the data type, it shouldn't be a problem as we already cast it to integer in the WMCore code, this line:
https://github.com/dmwm/WMCore/blob/3882e1ff7c55fd9a3054807f9ab8aebd8029d769/src/python/WMCore/Services/DBS/DBS3Reader.py#L891

however, I am getting a 400 Bad Request when I am trying to insert data into the testbed server with this call:
https://github.com/dmwm/WMCore/blob/3882e1ff7c55fd9a3054807f9ab8aebd8029d769/src/python/WMCore/Services/DBS/DBS3Reader.py#L892

I added some debugging and this is the data passed to that call:
```
2022-05-07 15:52:35,102:INFO:DBS3Reader:AMR childBlockName: /VBF_HHTo2G2Tau_CV_1_C2V_1_C3_0_TuneCP5_13TeV-powheg-pythia8/RunIISummer20UL16MiniAODAPVv2-HIG_RunIISummer20UL16MiniAODAPVv2_02457_0_SC_6Steps_PU_May2022_Val_Alanv1-v11/MINIAODSI
M#25f5a41e-00e8-4148-9f62-36e2125cef7f, listChildParent: [[661281877, 661282037], [661281877, 661282077], [661281877, 661282117], [661281877, 661281997], [661281917, 661282117], [661281917, 661282157], [661281917, 661282197], [661281917, 
661282237], [661281957, 661282277], [661281957, 661282317], [661281957, 661282397], [661281957, 661282357]]
``` 

Other than 400 bad request, I have nothing else to debug. Can you please check the server logs?

**Comment by vkuznet** [comment]
@amaltaro please do not mix different problems in single ticket, and open new one concerning data injection. The aggregation information is related to DBSClient, while injection is something I need to look at dbs Go server. Please provide me exact set of commands which leads to data injection problem.

**Comment by vkuznet** [comment]
Meanwhile, I'll create new release for DBSClient and put it on PyPi. Once it is released you'll need to update WMAgents or any other services which require aggregated information in listBlockTrio DBS API to use new DBSClient.

**Comment by amaltaro** [comment]
The information you need is provided in my last reply.

And I am reporting an issue where the root cause is the Go implementation of DBS. Fixing it in dbs3-client was only a choice that you made.

**Comment by vkuznet** [comment]
Alan, excuse me to be picky, but you are missing two different issues. You originally reported the different outputs with DBSClient while querying different DBS servers. This is what is issue you opened up. Then, when I fixed the DBSClient, you appended totally different issue with DBS3Reader`insertFileParents` API .So, in a future please open new issue and provide the following information:
- code base which you used with your DBS API
- input parameters for this API c
- the DBS instance you used for your call
- the actual DBS output

Here is how the issue should looks like: https://github.com/dmwm/dbs2go/issues/36, let's follow discussion over there.

**Comment by vkuznet** [comment]
Meanwhile, I uploaded DBSClient version 4.0.8 to PyPi so you can start using it.
