### ISSUE TITLE
REST API(s) input parameters need to be properly sanitized

### ISSUE THREAD

**Issue by amaltaro** [dmwm/dbs2go#38]
While testing a few things on my browser in an attempt to get a non 200 status code from the server, I tried this query:
https://cmsweb-testbed.cern.ch/dbs/int/global/DBSReader/blockparents?blockname=/NoBPTX/Run2018D-12Nov2019_UL2018-v1/MINIAOD%23be382968-82b7-4e65-b73f-57aa0b83d0e4

which apparently loads all the data from the database and actually crashed my browser. Note that the keyword argument is called `block_name`, not `blockname`.

If I try the same against the Python-based server, then it properly parses my input and does not proceed with the request (fails with 400 status code):
https://cmsweb-testbed.cern.ch/dbspy/int/global/DBSReader/blockparents?blockname=/NoBPTX/Run2018D-12Nov2019_UL2018-v1/MINIAOD%23be382968-82b7-4e65-b73f-57aa0b83d0e4

I only tested the `blockparents` API, but I'd highly recommend a thorough review of all the APIs to make sure that the misuse of the input parameters will not cause an outage of the service.

**Comment by vkuznet** [comment]
@amaltaro  thanks for reporting the issue. Indeed, we missed validation of parameters which are not accepted by DBS APIs and it may cause in some APIs the DB queries without WHERE clause constrain.

I committed the fix over here https://github.com/dmwm/dbs2go/commit/bd9b59b23ade93bf45026e7f08502b046f638f61 and we'll proceed with testing it on testbed. I'll update this ticket when validation will be done and we'll push changes to production.

**Comment by vkuznet** [comment]
FYI:  @d-ylee

**Comment by vkuznet** [comment]
Now, I deployed new server to testbed and here is how it behaves:
```
scurl -v https://cmsweb-testbed.cern.ch/dbs2go/blockparents?blockname=/NoBPTX/Run2018D-12Nov2019_UL2018-v1/MINIAOD%23be382968-82b7-4e65-b73f-57aa0b83d0e4
....
< HTTP/1.1 400 Bad Request
...
[{"error":{"reason":"invalid parameter(s)","message":"parameter 'blockname' is not accepted by 'blockparents' API","function":"dbs.parameters.CheckQueryParameters","code":118},"http":{"method":"GET","code":400,"timestamp":"2022-05-17 19:36:02.124345882 +0000 UTC m=+7.503813538","path":"/dbs2go/blockparents?blockname=/NoBPTX/Run2018D-12Nov2019_UL2018-v1/MINIAOD#be382968-82b7-4e65-b73f-57aa0b83d0e4","user_agent":"curl/7.29.0","x_forwarded_host":"cmsweb-testbed.cern.ch","x_forwarded_for":"188.185.115.163","remote_addr":"10.100.82.0:58008"},"exception":400,"type":"HTTPError","message":"DBSError Code:118 Description:DBS invalid parameter for the DBS API Function:dbs.parameters.CheckQueryParameters Message:parameter 'blockname' is not accepted by 'blockparents' API Error: invalid parameter(s)"}]
```
The error indicates that provided parameter  `blockname` is not accepted by `blocksparents` API.

**Comment by amaltaro** [comment]
@vkuznet Valentin, I did a simple and quick test of the `blockparents` API and it seems to be running properly, thanks!

Of course, I did not test:
* other APIs;
* this API through dbs3-client; and
* whether all the supported parameters are accepted.

and I trust you/Dennis have already done that; or it's not a concern. So, from my side feel free to proceed with this to production. Thanks again for the prompt action.

**Comment by vkuznet** [comment]
Deployed to production. For the record, the full list of allowed DBS parameters for all APIs can be found here: https://gitlab.cern.ch/cmsweb-k8s/services_config/-/blob/prod/dbs2go-global-r/parameters.json This file is parsed by DBS server codebase and rejects parameters outside of the appropriate list of particular API. Closing the issue now.
