### ISSUE TITLE
Add integration test for large run-lumis in bulkblocks2 API

### ISSUE THREAD

**Issue by vkuznet** [dmwm/dbs2go#46]
As described in the following tickets:
- https://github.com/dmwm/dbs2go/issues/45
- https://github.com/dmwm/WMCore/issues/11170
we identified the problem of missing run-lumi info in DBS database when injection is done with bulkblocks API. This only happened when concurrent injection of `FILE_LUMIS` was done via [insertFLChunk](https://github.com/dmwm/dbs2go/blob/master/dbs/filelumis.go#L330) function. This function is called via goroutine, i.e. it is run asynchronously, and even though it return the error this error was missing a final check to rollback the passed transaction argument. I applied appropriate fix in the following  https://github.com/dmwm/dbs2go/commit/5f92afbe85d80ada5ac868a7c4a6b5a644a3caca

Now, we need a new integration test to check if error may occur. To trigger such condition the number of run-lumis in input JSON should exceed `FileLumiChunkSize ` parameter which is set by default to 500, see here:
- https://github.com/dmwm/dbs2go/blob/master/dbs/bulkblocks2.go#L738
- https://github.com/dmwm/dbs2go/blob/master/dbs/bulkblocks2.go#L756
- https://github.com/dmwm/dbs2go/blob/master/web/config.go#L129

Therefore, we need the following to test concurrent injection:
- set lower limit of `FileLumiChunkSize`, e.g. to 20
- have `block.json` with `file_lumi_list` section where the number of run/lumis entries will exceed `FileLumiChunkSize`
- inject `block.json` via bulkblocks API, e.g.
```
# replace cmsweb-test with localhost, etc.
scurl -v -X POST -H "Content-type: application/json" -d @$PWD/block.json  https://cmsweb-testbed.cern.ch/dbs2go-writer/bulkblocks
```
- check that all run/lumis are present in provided `block_name`, e.g.
```
blk=/unittest_web_primary_ds_name_vk_test3/Summer2011-pstr-v10/GEN-SIM-RAW%23123456789
scurl "https://cmsweb-testbed.cern.ch/dbs2go/filelumis?block_name=$blk"
...
,{"event_count":0,"logical_file_name":"/store/data/a/b/A/a/1/vk_test3_abcd8.root","lumi_section_num":489,"run_num":1}
...
```

**Comment by d-ylee** [comment]
@vkuznet What other things should be added to the tests in order to complete this issue?

**Comment by vkuznet** [comment]
I think it is done via #47 , closing this one.
