### ISSUE TITLE
Document migration server behavior in edge cases

### ISSUE THREAD

**Issue by belforte** [dmwm/dbs2go#56]
with reference to https://github.com/dmwm/dbs2go/blob/master/docs/MigrationServer.md
It does not say what the output is when requesting migration for a block for which a migration was requested already.
Note that client code may use multiple processes/threads and thus the above may happen either because of concurrency or becasue a migration was submitted in an earlier processing.

Python based DBS has its way, and made CRAB code needing to rely in specifics like text in the messages [1] :-(
That surely was not optimal. 

It is quite possible that semantics is different in new server, e.g. no exceptions, also I do not remember that there was a cancel migration API,  or at least never used it. But simply we need a bit more details than "this is how to check status".

[1]
https://github.com/dmwm/CRABServer/blob/cf3fd79a508c798c99e39519996069e334c93d77/src/python/Publisher/TaskPublish.py#L274
https://github.com/dmwm/CRABServer/blob/cf3fd79a508c798c99e39519996069e334c93d77/src/python/Publisher/TaskPublish.py#L295
and note the special treatment for migration request in a different server thread
https://github.com/dmwm/CRABServer/blob/cf3fd79a508c798c99e39519996069e334c93d77/src/python/Publisher/TaskPublish.py#L320

**Comment by belforte** [comment]
reference to old  bahavior
https://github.com/dmwm/DBS/blob/14df8bbe8ee8f874fe423399b18afef911fe78c7/Client/src/python/dbs/apis/dbsClient.py#L1517-L1561

does not cover the issue of migration request already there on a different thread and need to look it up by block. I surely got that from Yuyi but do not have a 'paper trail'. 

indeed old DBS does not have a document explaining all this stuff, things are hidden in the code like
https://github.com/dmwm/DBS/blob/14df8bbe8ee8f874fe423399b18afef911fe78c7/Server/Python/src/dbs/business/DBSMigrate.py#L188-L189

All I can say is that current CRAB migration code was honed in collaboration with Yuyi N years ago and not changed since. It is not surprising that it may need changes now, I simply need to understand exactly which ones.

**Comment by vkuznet** [comment]
The new DBSMigration service process migration requests sequentially, therefore if someone submit the same request and it is already completed nothing will happen and you'll get the same status of migration. Therefore you don't need to look at edge case as you pointed out to specific string, and just check the migration status. I don't think I need to provide you more than that. And I think you don't need to modify CRAB code so far.

**Comment by belforte** [comment]
old migration server raised an exception when requested to migrate an already migrated jobs
new server instead completes successfully but returns `'migration_request_id': 0` and
'migration_report': 'Migration request for ... is already fulfilled, no blocks found for migration'

either behavior is OK, in the end. But I'd like to be reassured that current one is going to stay and change my code to be compatible.
JUst one question. Do I need to parse `migration_report` or may assume that whenever `0` is returned
as `migration_request_id` it means that block was already migrated ?

**Comment by vkuznet** [comment]
@belforte , the best way to detect migration request which asked for already existing data is to introduce new status code for that, e.g. 4. The status code 0 is default value and it can remain like that in different situation, e..g server error to parse json data. Since we do not have dedicated code for that you best option so far to rely on the message which btw I imitate from Python server.

If you want to use code I can easily introduce it, and this is my suggestion.

Meanwhile, I updated [migration document](https://github.com/dmwm/dbs2go/blob/master/docs/MigrationServer.md) to amplify how structures looks like.

**Comment by vkuznet** [comment]
about py exception during migration request, the exception is pure python stuff, in Go there is no exception. And, therefore for Go APIs either. Therefore, I suggest that you learn document structure of the APIs status and so far use message, and if you agree I'll provide new code for such use-case

**Comment by belforte** [comment]
I am happy to go w/o exceptions. We simply need to agree on protocol.
A new status code looks perfect, thanks !

**Comment by vkuznet** [comment]
I adde new code `4` (EXISTS_IN_DB) which will be assigned when migration block or dataset is already migrated. I deployed new codebase into testbed cluster and you can already use it for your tests.

**Comment by vkuznet** [comment]
Stefano, please let me know if I need to do anything with this issue, otherwise please close it.

**Comment by belforte** [comment]
thanks Valentin, closing.
