### ISSUE TITLE
migrationDelete arguments

### ISSUE THREAD

**Issue by belforte** [dmwm/dbs2go#59]
I stumbled on the fact that migrationDelete signature is changed from python server:
Now https://github.com/dmwm/dbs2go/blob/master/docs/apis.md :
```
    /remove
        removes given request from DBS migration server
        inputs

{"migration_rqst_id": 123, "create_by": "user"}
```
But before only `migration_rqst_id` was needed.
Of course I can change my code, but why does new server request the `created_by` ? migrationId is unique, I presume. And the information about who submitted the request is anyhow stored in the DB. Indeed the deletion code would simply issue a migrationStatus and pick this field from the output.

Old server was checking that DN of who deletes and who created the migrationId matched, which looks like a good idea but created a bit of extra work for DBS admin (Yuyi) when e.g. CRAB server was moved from one VM to another. Do you have same constrain ? Is that the reason to ask for the create_by ?

**Comment by vkuznet** [comment]
Stefano, you are right the `create_by` is not required from logic point of view. I checked python code it is not there, therefore I removed it from Go based code as well. I think I used it during development and left it unnoticed. I deployed new server on testbed and from now on you only need migration request id for removal request API. I also updated apis.md to reflect the change. I'm closing this ticket as resolved, feel free to re-open if necessary

**Comment by belforte** [comment]
Do you need to change DBSClient as well ?

**Comment by vkuznet** [comment]
I doubt we need to change anything in DBSClient, even if it sends create_by field the server is no longer look at it and it will be simply ignored.
