### ISSUE TITLE
problem requesting migration from prod/phys03 to int/phys03

### ISSUE THREAD

**Issue by belforte** [dmwm/dbs2go#69]
while testing, I hit this[1]. It is not a fully realistic use case since in real life we only migrate from prod/global to prod/phys03, yet I do not see why this should fail. Is this intentional ?
AFAICT the original dataset is fine (status=VALID)
https://cmsweb.cern.ch/das/request?view=list&limit=50&instance=prod%2Fphys03&input=%2FDYJetsToMM_EndcapMuFilter_M-50_TuneCP5_13TeV-madgraphMLM-pythia8_revering_noMissCsc%2Fmireveri-RunIISummer20UL18_DIGIPremix-a03b32ff24c52459822077d23898e252%2FUSER

A second order issue is that when using DBSClient, instead of the message in [1] I get a long wait followed by what looks like an error from FrontEnd i.e. a Proxy Error [2]

[1]
```
belforte@lxplus8s16/~> cat m.json 
{
"migration_url": "https://cmsweb-prod.cern.ch:8443/dbs/prod/phys03/DBSReader",
"migraton_input": "/DYJetsToMM_EndcapMuFilter_M-50_TuneCP5_13TeV-madgraphMLM-pythia8_revering_noMissCsc/mireveri-RunIISummer20UL18_DIGIPremix-a03b32ff24c52459822077d23898e252/USER#96ecdc3d-86a0-4168-b32d-2f24f9ac6077"
}
belforte@lxplus8s16/~> curl --cert $X509_USER_PROXY  --key $X509_USER_PROXY -H "Content-Type: application/json" -d@m.json "https://cmsweb-testbed.cern.ch:8443/dbs/int/phys03/DBSMigrate/submit"
[{"error":{"reason":"dataset  has status ","message":"not allowed for migration","function":"dbs.migrate.SubmitMigration","code":125},"http":{"method":"POST","code":400,"timestamp":"2022-07-27 23:12:04.405434885 +0000 UTC m=+189113.409541442","path":"/dbs/int/phys03/DBSMigrate/submit","user_agent":"curl/7.70.0","x_forwarded_host":"cmsweb-testbed.cern.ch:8443","x_forwarded_for":"188.185.34.228","remote_addr":"10.100.222.192:60621"},"exception":400,"type":"HTTPError","message":"DBSError Code:125 Description:DBS Migration error Function:dbs.migrate.SubmitMigration Message:not allowed for migration Error: dataset  has status "}]belforte@lxplus8s16/~> 
```

[2]
```
DBS3 exception: HTTP Error 502: 
URL=https://cmsweb-testbed.cern.ch:8443/dbs/int/phys03/DBSMigrate/submit
Code=502
Message=Proxy Error
Header=HTTP/1.1 502 Proxy Error
Date: Wed, 27 Jul 2022 23:00:30 GMT
Server: Apache
Content-Length: 472
Content-Type: text/html; charset=iso-8859-1

Body=<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>502 Proxy Error</title>
</head><body>
<h1>Proxy Error</h1>
<p>The proxy server received an invalid
response from an upstream server.<br />
The proxy server could not handle the request <em><a href="/auth/complete/dbs/int/phys03/DBSMigrate/submit">POST&nbsp;/auth/complete/dbs/int/phys03/DBSMigrate/submit</a></em>.<p>
Reason: <strong>Error reading from remote server</strong></p></p>
</body></html>
```

**Comment by vkuznet** [comment]
Stefano, do you still experience original issue of migrating from prod/phys03 to int/phys03? The proxy has its own ticket https://github.com/dmwm/dbs2go/issues/72 and we should separate it from original one.

**Comment by belforte** [comment]
I have not checked lately. But you are correct that I put two issues in one. Let me try.

**Comment by belforte** [comment]
error is still there, you can easily reproduce it with the curl example at the top of this issue
```
belforte@lxplus757/migration> curl --cert $X509_USER_PROXY  --key $X509_USER_PROXY -H "Content-Type: application/json" -d@m.json "https://cmsweb-testbed.cern.ch:8443/dbs/int/phys03/DBSMigrate/submit"
[{"error":{"reason":"dataset  has status ","message":"not allowed for migration","function":"dbs.migrate.SubmitMigration","code":125},"http":{"method":"POST","code":400,"timestamp":"2022-08-16 14:22:00.433956492 +0000 UTC m=+8197.421742634","path":"/dbs/int/phys03/DBSMigrate/submit","user_agent":"curl/7.70.0","x_forwarded_host":"cmsweb-testbed.cern.ch:8443","x_forwarded_for":"188.185.7.99","remote_addr":"10.100.232.128:27458"},"exception":400,"type":"HTTPError","message":"DBSError Code:125 Description:DBS Migration error Function:dbs.migrate.SubmitMigration Message:not allowed for migration Error: dataset  has status "}]
```

maybe user datasets in PHY03 do not have production status ?
Yet looking in DAS at https://cmsweb.cern.ch/das/request?view=list&limit=50&instance=prod%2Fphys03&input=%2FDYJetsToMM_EndcapMuFilter_M-50_TuneCP5_13TeV-madgraphMLM-pythia8_revering_noMissCsc%2Fmireveri-RunIISummer20UL18_DIGIPremix-a03b32ff24c52459822077d23898e252%2FUSER the dataset status is VALID.

same from `dasgoclient --query 'dataset dataset=/DYJetsToMM_EndcapMuFilter_M-50_TuneCP5_13TeV-madgraphMLM-pythia8_revering_noMissCsc/mireveri-RunIISummer20UL18_DIGIPremix-a03b32ff24c52459822077d23898e252/USER instance=prod/phys03' --json`

**Comment by vkuznet** [comment]
Stefano, I looked at this failure and now I see the issue. I want to share details with you that you'll be aware. The block you provided in you migration request has 7075 parents (!!!), which needs to be look-up recursively from DBS server. First, I have no idea if having 7K parents has any meaning, but on my laptop it took 1h to get all parents. Said that, the blockparents API from my laptop takes 1sec for one block, but since we have 7K blocks and there is some concurrency in place the total time spent was 1h. I measured time of individual HTTP call on lxplus and it takes 0.04s instead of 1sec (which is significant boost), but making a simple math it will take around 300sec for 7K calls to resolve all parents which is our FE threshold. As such, I'm not surprised that this request fails with HTTP proxy error.

Now, since you know all details I need to understand how often we may have such crazy requests. If having O(10K) parents is "usual" pattern I need to change architecture of the code. So far I based on assumption that we have O(100) parents per block/dataset, but not 100 times more. While I will think about the architectural choices please let me know your feedback on this and similar use-cases (if we need to handle them). I'm really curious if this is an outlier or it is something we should support.

**Comment by belforte** [comment]
gut reaction: this is fully crazy and we need to think of a way to prevent it !!

But it is curious, so let's not rush to any conclusion and let me look. On the good side, there is no need to migrate from one phys03 to another in "real life", and no limit to users "creativity".

Surely do not spend time in trying to address this use case.

But the error comes immediately and is shared by other datasets, are you sure that it is due to the number of parents ? Or is there an accidental coincidence ?

Yeah.. I guess that I should try to migrate some "known, normal dataset from-to the same DBS instances to verify that it works and close the issue.

**Comment by belforte** [comment]
hmm.. looking up the block at the top, it  has 100 files, each file seem to have 3 parents.
Sort of "normal". Although this dataset suffers of the common problem of having lots of files because each file has few events.
And looking up parents via DAS I get 166 parent blocks.

Maybe I start to see the problem, those blocks have more parents, e.g. 61 for the first one. I guess user reprocessed her/his own initial MC dataset several times, mixing things so that in the end each final block likely depends on all blocks in "primal dataset". Most likely the overall amount of data to migrate can't be very large (all in all this horrendous structure somehow exists in prod/phys03 already). But the ancestor combinatorics is exploding.

That said, I do not know exactly how this dataset was created, so how likely is that we can have similar problem in datasets derived from production data which may surface when migrating from prod to phys03. Somehow we have parent/child relationships which "are too complex to fully list across generations".

It looks like we may be better off by simply identifying ancestor datasets and migrating those, so a block with 100 parent blocks will become a block with 2 parent datasets which may have a couple parents each at most.

Of course would be good to know which strategy is used by python server, which may have been tuned on real data, to avoid rediscovering things one at a time.

Given that our priority now is to put new server in production, I suggest not to worry about migrations which start from phys03, based on the simple rule "who knows what crazy stuff users have put in there, let's stick to Production output where at least we have some control on". And think carefully before evaluating possible different strategies for the new migration server, which may be somehow naive, but all in all appears to work.

**Comment by vkuznet** [comment]
Please see this explanation to address this issue: https://github.com/dmwm/dbs2go/issues/68#issuecomment-1218168500

**Comment by vkuznet** [comment]
closing as resolved before migration to k8s.
