### ISSUE TITLE
migrations keep failing

### ISSUE THREAD

**Issue by belforte** [dmwm/dbs2go#78]
we have started to remove and resubmit failed migrations.
Only tried 3 so far. One went OK. But two kepf failing.
Latest example:
removed `3309489` and submitted request for same block in `3346244`

It was initially in status 5 (as expected) but when tested again after 1 minute, status 3 with retry_count 2

[crab3@crab-prod-tw01 migrations]$ scurl  https://cmsweb-prod.cern.ch:8443/dbs/prod/phys03/DBSMigrate/status?migration_rqst_id=3346244
[
{"create_by":"/DC=ch/DC=cern/OU=computers/CN=tw/crab-prod-tw01.cern.ch","creation_date":1661786028,"last_modification_date":1661786222,"last_modified_by":"/DC=ch/DC=cern/OU=computers/CN=tw/crab-prod-tw01.cern.ch","migration_input":"/ST_t-channel_top_5f_InclusiveDecays_TuneCP5_13TeV-powheg-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v1/MINIAODSIM#fede6d16-1703-444e-837a-e047e688678f","migration_request_id":3346244,"migration_server":"dbs2go-phys03-m-57cfbb9569-f9c8w","migration_status":3,"migration_url":"https://cmsweb-prod.cern.ch/dbs/prod/global/DBSReader","retry_count":2}

and eventually it reached status 9

[crab3@crab-prod-tw01 migrations]$ scurl  https://cmsweb-prod.cern.ch:8443/dbs/prod/phys03/DBSMigrate/status?migration_rqst_id=3346244
[
{"create_by":"/DC=ch/DC=cern/OU=computers/CN=tw/crab-prod-tw01.cern.ch","creation_date":1661786028,"last_modification_date":1661786467,"last_modified_by":"/DC=ch/DC=cern/OU=computers/CN=tw/crab-prod-tw01.cern.ch","migration_input":"/ST_t-channel_top_5f_InclusiveDecays_TuneCP5_13TeV-powheg-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v1/MINIAODSIM#fede6d16-1703-444e-837a-e047e688678f","migration_request_id":3346244,"migration_server":"dbs2go-phys03-m-57cfbb9569-f9c8w","migration_status":9,"migration_url":"https://cmsweb-prod.cern.ch/dbs/prod/global/DBSReader","retry_count":3}
]

the odd thing is that there is not trace of any activity in migration server log:
belforte@vocms0750/dbs-logs> pwd
/cephfs/product/dbs-logs
belforte@vocms0750/dbs-logs> grep 3346244 dbs2go-phys03-migration-8449c6c487-shgzs.log-20220829
does not find anything.

Why did it fail then ? Is there another process around which may have acted on it ?

**Comment by vkuznet** [comment]
Stefano, I don't see that it was picked up by migration server. But I tested it locally and everything was fine. I suspect that because it was in status=5 we have an issue. Since now it is in status=9, I suggest to remove it again via `remove` API and try again. I want to see how now it will go. If you do not mind I can do it myself which will make it easier since I can see the entire process from both ends. Please confirm and I'll try to remove and then re-submit it on my own (using my DN).

**Comment by belforte** [comment]
please feel free to do this yourself. It is better indeed.
I am very puzzled as well, since I did not find anything in logs.

**Comment by belforte** [comment]
sorry for late reply. network glitch

**Comment by belforte** [comment]
beware full story: this happened to Dario already this morning, I couldn't believe it so I removed his second failed attempt, submitted again, and succeeded immediately. So I blamed a server restart (e.g. to push the fix for remove API) and tried a new one myself, and got what reported above. Could the problem be intermittent ?

**Comment by belforte** [comment]
should you need a few more failed migrations to try, here they are (we have >900 atm)
```
3309489
3309689
3311420
3311339
3318983
3318941
3311350
3311212
3308907
3309337
```

**Comment by vkuznet** [comment]
Stefano, I'm working on this issue, and I do see failed migration. I need more time, may be few days as the debugging is very tricky in asynchronous environment.

**Comment by belforte** [comment]
Thanks Valentin. I understand. Lets us know if there's anything we can do to help. If you need to do things like turning off servers, starting new ones for debugging...feel free.
Do you think that it is worth that we try removing and recreating those failed migrations anyhow, in case some get cleared up ? Or better not make noise in logs ?
I can also completely stop migrations, if that helps.
FYI @mapellidario

**Comment by vkuznet** [comment]
@belforte , @mapellidario , finally I identified the issue. We left running python migration server on one of the VM and we got overlap between two different servers implementation. Even though I was adding more debugging and fixed minor bugs this was the real issue. Once @muhammadimranfarooqi shut it down I was able successfully migrate this block `/ST_t-channel_top_5f_InclusiveDecays_TuneCP5_13TeV-powheg-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v1/MINIAODSIM#fede6d16-1703-444e-837a-e047e688678f` which Stefano referred in the ticket. I think now things will go smoothly.

Please do the following:
- pick up one of your recent failed migration request with status 9, `migration_request_id= 3309337` or `/QCD_Pt-800To1000_MuEnrichedPt5_TuneCP5_13TeV-pythia8/RunIISummer20UL17MiniAODv2-106X_mc2017_realistic_v9-v2/MINIAODSIM#61429aca-fb1f-45c0-9885-456b7137e1da` and remove it from the system
```
scurl -v -H "Content-type: application/json" -d'{"migration_rqst_id":3309337 "https://cmsweb-prod.cern.ch/dbs/prod/phys03/DBSMigrate/remove"
```
- then create new migration request with this block and submit it
- check that it works
- after that you can delete all failed migration and res-submit them.

Let me know how it will go.

**Comment by belforte** [comment]
I am exercising things now manually (i.e. low rate) and it is working :-)

I am now going to crank up a bit with some bash loop.

Thanks. I had thought about the possibility of another server running at same time yesterday, but could not find any other logs on vocms0750:/cephfs... and did not realize that VM cluster stuff is elsewhere.
In the end on that cluster we (should) only run DBSReaders, but dbs2go reader is well validated now, time to get rid of that thing ?

**Comment by belforte** [comment]
doing finely.

**Comment by vkuznet** [comment]
We keep them around just in case to avoid painful RPM based installation procedure. Once we'll fully migrate then we can decommission python servers. What we should be careful about is running multiple servers talking to the same DB which as we can see can lead to mysterious issues with missing log info ;)

**Comment by vkuznet** [comment]
Stefano, and now you can easily see in dbs2go-phys03-migration all migration processing, e..g pay attention to messages like 
```
[2022-08-30 00:58:45.721551459 +0000 UTC m=+10385.641106738] migrate.go:1107: updated migration request 3346947 with status 2
```
which indicates the final status assigned to migration.

**Comment by vkuznet** [comment]
And, for some requests I see this:
```
[2022-08-30 02:00:00.737969386 +0000 UTC m=+14060.657524659] migrate.go:1099: insert block dump record failed with DBSError Code:101 Description:DBS DB error Function:dbs.bulkblocks.InsertBulkBlocksConcurrently Message:Data already exist in DBS  Error: Block /TTToHadronic_TuneCP5_13TeV-powheg-pythia8/RunIISummer20UL16RECOAPV-106X_mcRun2_asymptotic_preVFP_v8-v2/AODSIM#a553c9d0-5c9a-4eed-b756-f22e99b4b597 already exists
....
[2022-08-30 02:00:00.826899972 +0000 UTC m=+14060.746455247] migrate.go:1107: updated migration request 3346969 with status 3
```
so, the client is trying to re-inject existing blocks. At least now I can clearly see the reason why migration fails or not and all the info about the migration request.

**Comment by vkuznet** [comment]
Let me know if we can close this issue now.

**Comment by belforte** [comment]
that should be harmless, right ? It is likely that Publisher is retrying failing tasks at same time.

**Comment by belforte** [comment]
I remove/recreated about 60 migrations now. All OK. You can close. I will go through all the others. WIll let you know of any problem.

**Comment by vkuznet** [comment]
ok, yes these failed migrations are harmless since block is already in DBS. Those can be simply ignored. Closing now this issue.

**Comment by vkuznet** [comment]
And, for the record, I scale down dbs2go-phys03-m and dbs2go-phys03-migration to 1 replica on k8s, with the rate I see it should be sufficient and we can scale up at any time. Using one replica had big advantage during debugging since log is only in one file.
